version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  redis-container:
    image: "redis:alpine"
    volumes:
      - $PWD/redis-data:/var/lib/redis
